pipeline:

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-management-notprod
      - INSECURE_SKIP_TLS_VERIFY=true
      - JIRA_HOME_VOLUME_SIZE=5Gi
      - HOSTNAME=jira.notprod.dq.homeoffice.gov.uk
      - DATABASE_SECRET_NAME=dq-jira-notprod-rds-access
      - DATABASE_SCHEMA_NAME=public
    commands:
      - export KUBE_TOKEN=$$NOTPROD_KUBE_TOKEN
      - export KUBE_SERVER=$$NOTPROD_KUBE_SERVER
      - kd -f network-policy.yml -f pvc.yml -f deployment.yml -f service.yml -f ingress.yml
    secrets:
      - NOTPROD_KUBE_TOKEN
      - NOTPROD_KUBE_SERVER
    when:
      event: [push, tag, deployment]



  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    environment:
      - KUBE_NAMESPACE=dq-management
      - INSECURE_SKIP_TLS_VERIFY=true
      - JIRA_HOME_VOLUME_SIZE=25Gi
      - HOSTNAME=jira.prod.dq.homeoffice.gov.uk
      - DATABASE_SECRET_NAME=dq-management-jira-rds-access
      - DATABASE_SCHEMA_NAME=public
    commands:
      - export KUBE_TOKEN=$$PROD_KUBE_TOKEN
      - export KUBE_SERVER=$$PROD_KUBE_SERVER
      - kd -f network-policy.yml -f pvc.yml -f deployment.yml -f service.yml -f ingress.yml
    secrets:
      - PROD_KUBE_TOKEN
      - PROD_KUBE_SERVER
    when:
      environment: production
      event: deployment
