---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jira
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jira
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: jira
        image: quay.io/ukhomeofficedigital/jira-docker:7.9.1
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: 2
            memory: 3.2Gi
          requests:
            cpu: 1.5
            memory: 2Gi
        volumeMounts:
          - mountPath: /var/atlassian/jira
            name: jira
            subPath: home
          - mountPath: /opt/atlassian/jira/conf
            subPath: config
            name: jira
          - mountPath: /opt/atlassian/jira/logs
            subPath: logs
            name: jira

      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8080'
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443

      volumes:
        - name: jira
          persistentVolumeClaim:
            claimName: jira
