---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jira
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: jira
    spec:
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
      containers:
      - name: jira
        image: quay.io/ukhomeofficedigital/jira-docker:7.12.0
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: 2
            memory: 3.2Gi
          requests:
            cpu: 1.5
            memory: 2Gi
        env:
          - name: SERVER_PORT
            value: '8080'
          - name: SERVER_PROXY_NAME
            value: {{ .HOSTNAME }}
          - name: SERVER_PROXY_PORT
            value: '443'
          - name: SERVER_REDIRECT_PORT
            value: '10443'
          - name: DATABASE_HOST
            valueFrom:
              secretKeyRef:
                name: {{ .DATABASE_SECRET_NAME }}
                key: endpoint
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .DATABASE_SECRET_NAME }}
                key: database_name
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .DATABASE_SECRET_NAME }}
                key: password
          - name: DATABASE_PORT
            valueFrom:
              secretKeyRef:
                name: {{ .DATABASE_SECRET_NAME }}
                key: port
          - name: DATABASE_SCHEMA_NAME
            value: {{ .DATABASE_SCHEMA_NAME }}
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .DATABASE_SECRET_NAME }}
                key: username
          - name: BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: {{ .AWS_BUCKET_SECRET_NAME }}
                key: bucket_name
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: {{ .AWS_BUCKET_SECRET_NAME }}
                key: access_key_id
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .AWS_BUCKET_SECRET_NAME }}
                key: secret_access_key
        volumeMounts:
          - mountPath: /var/atlassian/jira
            name: jira


      - name: proxy
        image: quay.io/ukhomeofficedigital/nginx-proxy
        securityContext:
          runAsNonRoot: true
        env:
          - name: PROXY_SERVICE_HOST
            value: 'http://127.0.0.1'
          - name: PROXY_SERVICE_PORT
            value: '8080'
          - name: LOG_FORMAT_NAME
            value: 'json'
          - name: NAXSI_USE_DEFAULT_RULES
            value: 'FALSE'
        ports:
          - name: https
            containerPort: 10443

      - name: test
        image: quay.io/ukhomeofficedigital/nginx-proxy
        securityContext:
          runAsNonRoot: true
        volumeMounts:
          - mountPath: /var/atlassian/jira
            name: jira

      volumes:
        - name: jira
          persistentVolumeClaim:
            claimName: jira
