---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jira-ingress
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    stable.k8s.psg.io/kcm.provider: http
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - {{ .HOSTNAME}}
    secretName: jira-tls
  rules:
  - host: {{ .HOSTNAME}}
    http:
      paths:
      - backend:
          serviceName: jira-service
          servicePort: 443
        path: /
