---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jira-ingress
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/enabled: "true"
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - hosts:
    - {{ .HOSTNAME}}
    secretName: jira-tls
  rules:
  - host: {{ .HOSTNAME}}
    http:
      paths:
      - backend:
          serviceName: jira-service
          servicePort: https
        path: /
