---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    kubernetes.io/ingress.class: "nginx-external"
    kubernetes.io/tls-acme: "true"
  name: jira-ingress
spec:
  rules:
  - host: {{ .HOSTNAME }}
    http:
      paths:
      - backend:
          serviceName: jira-service
          servicePort: https
        path: /
  tls:
  - secretName: jira-tls
    hosts:
    - {{ .HOSTNAME }}