kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jira-pg96
  annotations:
    volume.beta.kubernetes.io/storage-class: gp2-encrypted
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .JIRA_HOME_VOLUME_SIZE }}
