apiVersion: v1
kind: Secret
metadata:
  name: {{ .AWS_BUCKET_SECRET_NAME }}
type: Opaque
data:
  bucket_name: {{ .BUCKET_NAME }}
  access_key_id: {{ .ACCESS_KEY_ID }}
  secret_access_key: {{ .SECRET_ACCESS_KEY }}