---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: jira-service-pg96
  name: jira-service-pg96
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    name: jira-pg96
